package cn.silver.framework.file.constant;

import lombok.extern.slf4j.Slf4j;
import org.apache.commons.collections.MapUtils;
import org.apache.commons.lang3.StringUtils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.*;

/**
 * @Description: 文件上下文类型常量
 * @Author: Silver
 * @Date: 2021-04-21
 */
@Slf4j
public class ContentTypeConstant {
    /**
     * 两种初始化Map常量
     * 两种初始化Map常量
     * 1.new HashMap
     * 2.static 静态代码块
     */
    private static final Map<String, String> allContentType = new HashMap<>(700);
    private static final Map<String, String> usedContentType = new HashMap<>(20);

    private static final Map<String, List<String>> content = new HashMap<>(5);

    static {
        initContent();
        initUsedContentType();
        initAllContentType();
    }

    //通过key获取ContentType值
    public static String getContentType(String ext) {
        return allContentType.get(ext);
    }

    public static String getFileTypeByContent(String contentType) {
        return usedContentType.containsKey(contentType) ? usedContentType.get(contentType) : "other";
    }

    public static Map<String, String> getUsedContentType() {
        if (MapUtils.isEmpty(usedContentType)) {
            initUsedContentType();
        }
        return usedContentType;
    }

    public static Map<String, List<String>> getContent() {
        if (MapUtils.isEmpty(content)) {
            initContent();
        }
        return content;
    }

    public static Map<String, String> getAllContentType() {
        if (MapUtils.isEmpty(allContentType)) {
            initAllContentType();
        }
        return allContentType;
    }

    public static String getFormat(File file) {
        String format;
        try {
            format = Files.probeContentType(file.toPath());
            if (StringUtils.isBlank(format)) {
                format = allContentType.getOrDefault(file.getName().substring(file.getName().lastIndexOf(".")), "application/pdf");
            }
        } catch (IOException e) {
            log.error("获取上下文类型信息失败，开始从静态缓存区获取", e);
            format = allContentType.getOrDefault(file.getName().substring(file.getName().lastIndexOf(".")), "application/pdf");
        }
        return format;
    }

    private static void initContent() {
        List<String> docContent = new ArrayList<>();
        docContent.add("application/msword");
        docContent.add("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        content.put("word", docContent);
        List<String> excelContent = new ArrayList<>();
        excelContent.add("application/vnd.ms-excel");
        excelContent.add("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        content.put("excel", docContent);
        List<String> powerPointContent = new ArrayList<>();
        powerPointContent.add("application/vnd.ms-powerpoint");
        powerPointContent.add("application/vnd.openxmlformats-officedocument.presentationml.presentation");
        content.put("ppt", docContent);
        content.put("pdf", Arrays.asList("application/pdf"));
        List<String> pictrureContent = new ArrayList<>();
        pictrureContent.add("image/bmp");
        pictrureContent.add("image/gif");
        pictrureContent.add("image/jpeg");
        pictrureContent.add("image/tiff");
        pictrureContent.add("image/png");
        pictrureContent.add("image/svg+xml");
        pictrureContent.add("image/svg+xml-compressed");
        content.put("pictrue", pictrureContent);
    }

    private static void initUsedContentType() {
        usedContentType.put("application/msword", "word");
        usedContentType.put("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "word");
        usedContentType.put("application/vnd.ms-excel", "excel");
        usedContentType.put("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "excel");
        usedContentType.put("application/vnd.ms-powerpoint", "ppt");
        usedContentType.put("application/vnd.openxmlformats-officedocument.presentationml.presentation", "ppt");
        usedContentType.put("application/pdf", "pdf");
        usedContentType.put("image/bmp", "pictrue");
        usedContentType.put("image/gif", "pictrue");
        usedContentType.put("image/jpeg", "pictrue");
        usedContentType.put("image/png", "pictrue");
        usedContentType.put("image/svg+xml", "pictrue");
        usedContentType.put("image/svg+xml-compressed", "pictrue");
        usedContentType.put("image/tiff", "tiff");
        usedContentType.put("application/x-zip-compressed", "压缩包");
        usedContentType.put("ws", "ws");
        usedContentType.put("xunwen", "xunwen");
        usedContentType.put("kanyan", "kanyan");
        usedContentType.put("bianren", "bianren");
    }

    private static void initAllContentType() {
        allContentType.put("jpg", "image/jpeg");
        allContentType.put("jpeg", "image/jpeg");
        allContentType.put("load", "text/html");
        allContentType.put("123", "application/vnd.lotus-1-2-3");
        allContentType.put("3ds", "image/x-3ds");
        allContentType.put("3g2", "video/3gpp");
        allContentType.put("3ga", "video/3gpp");
        allContentType.put("3gp", "video/3gpp");
        allContentType.put("3gpp", "video/3gpp");
        allContentType.put("602", "application/x-t602");
        allContentType.put("669", "audio/x-mod");
        allContentType.put("7z", "application/x-7z-compressed");
        allContentType.put("a", "application/x-archive");
        allContentType.put("aac", "audio/mp4");
        allContentType.put("abw", "application/x-abiword");
        allContentType.put("abw.crashed", "application/x-abiword");
        allContentType.put("abw.gz", "application/x-abiword");
        allContentType.put("ac3", "audio/ac3");
        allContentType.put("ace", "application/x-ace");
        allContentType.put("adb", "text/x-adasrc");
        allContentType.put("ads", "text/x-adasrc");
        allContentType.put("afm", "application/x-font-afm");
        allContentType.put("ag", "image/x-applix-graphics");
        allContentType.put("ai", "application/illustrator");
        allContentType.put("aif", "audio/x-aiff");
        allContentType.put("aifc", "audio/x-aiff");
        allContentType.put("aiff", "audio/x-aiff");
        allContentType.put("al", "application/x-perl");
        allContentType.put("alz", "application/x-alz");
        allContentType.put("amr", "audio/amr");
        allContentType.put("ani", "application/x-navi-animation");
        allContentType.put("anim[1-9j]", "video/x-anim");
        allContentType.put("anx", "application/annodex");
        allContentType.put("ape", "audio/x-ape");
        allContentType.put("arj", "application/x-arj");
        allContentType.put("arw", "image/x-sony-arw");
        allContentType.put("as", "application/x-applix-spreadsheet");
        allContentType.put("asc", "text/plain");
        allContentType.put("asf", "video/x-ms-asf");
        allContentType.put("asp", "application/x-asp");
        allContentType.put("ass", "text/x-ssa");
        allContentType.put("asx", "audio/x-ms-asx");
        allContentType.put("atom", "application/atom+xml");
        allContentType.put("au", "audio/basic");
        allContentType.put("avi", "video/x-msvideo");
        allContentType.put("aw", "application/x-applix-word");
        allContentType.put("awb", "audio/amr-wb");
        allContentType.put("awk", "application/x-awk");
        allContentType.put("axa", "audio/annodex");
        allContentType.put("axv", "video/annodex");
        allContentType.put("bak", "application/x-trash");
        allContentType.put("bcpio", "application/x-bcpio");
        allContentType.put("bdf", "application/x-font-bdf");
        allContentType.put("bib", "text/x-bibtex");
        allContentType.put("bin", "application/octet-stream");
        allContentType.put("blend", "application/x-blender");
        allContentType.put("blender", "application/x-blender");
        allContentType.put("bmp", "image/bmp");
        allContentType.put("bz", "application/x-bzip");
        allContentType.put("bz2", "application/x-bzip");
        allContentType.put("c", "text/x-csrc");
        allContentType.put("c++", "text/x-c++src");
        allContentType.put("cab", "application/vnd.ms-cab-compressed");
        allContentType.put("cb7", "application/x-cb7");
        allContentType.put("cbr", "application/x-cbr");
        allContentType.put("cbt", "application/x-cbt");
        allContentType.put("cbz", "application/x-cbz");
        allContentType.put("cc", "text/x-c++src");
        allContentType.put("cdf", "application/x-netcdf");
        allContentType.put("cdr", "application/vnd.corel-draw");
        allContentType.put("cer", "application/x-x509-ca-cert");
        allContentType.put("cert", "application/x-x509-ca-cert");
        allContentType.put("cgm", "image/cgm");
        allContentType.put("chm", "application/x-chm");
        allContentType.put("chrt", "application/x-kchart");
        allContentType.put("class", "application/x-java");
        allContentType.put("cls", "text/x-tex");
        allContentType.put("cmake", "text/x-cmake");
        allContentType.put("cpio", "application/x-cpio");
        allContentType.put("cpio.gz", "application/x-cpio-compressed");
        allContentType.put("cpp", "text/x-c++src");
        allContentType.put("cr2", "image/x-canon-cr2");
        allContentType.put("crt", "application/x-x509-ca-cert");
        allContentType.put("crw", "image/x-canon-crw");
        allContentType.put("cs", "text/x-csharp");
        allContentType.put("csh", "application/x-csh");
        allContentType.put("css", "text/css");
        allContentType.put("cssl", "text/css");
        allContentType.put("csv", "text/csv");
        allContentType.put("cue", "application/x-cue");
        allContentType.put("cur", "image/x-win-bitmap");
        allContentType.put("cxx", "text/x-c++src");
        allContentType.put("d", "text/x-dsrc");
        allContentType.put("dar", "application/x-dar");
        allContentType.put("dbf", "application/x-dbf");
        allContentType.put("dc", "application/x-dc-rom");
        allContentType.put("dcl", "text/x-dcl");
        allContentType.put("dcm", "application/dicom");
        allContentType.put("dcr", "image/x-kodak-dcr");
        allContentType.put("dds", "image/x-dds");
        allContentType.put("deb", "application/x-deb");
        allContentType.put("der", "application/x-x509-ca-cert");
        allContentType.put("desktop", "application/x-desktop");
        allContentType.put("dia", "application/x-dia-diagram");
        allContentType.put("diff", "text/x-patch");
        allContentType.put("divx", "video/x-msvideo");
        allContentType.put("djv", "image/vnd.djvu");
        allContentType.put("djvu", "image/vnd.djvu");
        allContentType.put("dng", "image/x-adobe-dng");
        allContentType.put("doc", "application/msword");
        allContentType.put("docbook", "application/docbook+xml");
        allContentType.put("docm", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        allContentType.put("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        allContentType.put("dot", "text/vnd.graphviz");
        allContentType.put("dsl", "text/x-dsl");
        allContentType.put("dtd", "application/xml-dtd");
        allContentType.put("dtx", "text/x-tex");
        allContentType.put("dv", "video/dv");
        allContentType.put("dvi", "application/x-dvi");
        allContentType.put("dvi.bz2", "application/x-bzdvi");
        allContentType.put("dvi.gz", "application/x-gzdvi");
        allContentType.put("dwg", "image/vnd.dwg");
        allContentType.put("dxf", "image/vnd.dxf");
        allContentType.put("e", "text/x-eiffel");
        allContentType.put("egon", "application/x-egon");
        allContentType.put("eif", "text/x-eiffel");
        allContentType.put("el", "text/x-emacs-lisp");
        allContentType.put("emf", "image/x-emf");
        allContentType.put("emp", "application/vnd.emusic-emusic_package");
        allContentType.put("ent", "application/xml-external-parsed-entity");
        allContentType.put("eps", "image/x-eps");
        allContentType.put("eps.bz2", "image/x-bzeps");
        allContentType.put("eps.gz", "image/x-gzeps");
        allContentType.put("epsf", "image/x-eps");
        allContentType.put("epsf.bz2", "image/x-bzeps");
        allContentType.put("epsf.gz", "image/x-gzeps");
        allContentType.put("epsi", "image/x-eps");
        allContentType.put("epsi.bz2", "image/x-bzeps");
        allContentType.put("epsi.gz", "image/x-gzeps");
        allContentType.put("epub", "application/epub+zip");
        allContentType.put("erl", "text/x-erlang");
        allContentType.put("es", "application/ecmascript");
        allContentType.put("etheme", "application/x-e-theme");
        allContentType.put("etx", "text/x-setext");
        allContentType.put("exe", "application/x-ms-dos-executable");
        allContentType.put("exr", "image/x-exr");
        allContentType.put("ez", "application/andrew-inset");
        allContentType.put("f", "text/x-fortran");
        allContentType.put("f90", "text/x-fortran");
        allContentType.put("f95", "text/x-fortran");
        allContentType.put("fb2", "application/x-fictionbook+xml");
        allContentType.put("fig", "image/x-xfig");
        allContentType.put("fits", "image/fits");
        allContentType.put("fl", "application/x-fluid");
        allContentType.put("flac", "audio/x-flac");
        allContentType.put("flc", "video/x-flic");
        allContentType.put("fli", "video/x-flic");
        allContentType.put("flv", "video/x-flv");
        allContentType.put("flw", "application/x-kivio");
        allContentType.put("fo", "text/x-xslfo");
        allContentType.put("for", "text/x-fortran");
        allContentType.put("g3", "image/fax-g3");
        allContentType.put("gb", "application/x-gameboy-rom");
        allContentType.put("gba", "application/x-gba-rom");
        allContentType.put("gcrd", "text/directory");
        allContentType.put("ged", "application/x-gedcom");
        allContentType.put("gedcom", "application/x-gedcom");
        allContentType.put("gen", "application/x-genesis-rom");
        allContentType.put("gf", "application/x-tex-gf");
        allContentType.put("gg", "application/x-sms-rom");
        allContentType.put("gif", "image/gif");
        allContentType.put("glade", "application/x-glade");
        allContentType.put("gmo", "application/x-gettext-translation");
        allContentType.put("gnc", "application/x-gnucash");
        allContentType.put("gnd", "application/gnunet-directory");
        allContentType.put("gnucash", "application/x-gnucash");
        allContentType.put("gnumeric", "application/x-gnumeric");
        allContentType.put("gnuplot", "application/x-gnuplot");
        allContentType.put("gp", "application/x-gnuplot");
        allContentType.put("gpg", "application/pgp-encrypted");
        allContentType.put("gplt", "application/x-gnuplot");
        allContentType.put("gra", "application/x-graphite");
        allContentType.put("gsf", "application/x-font-type1");
        allContentType.put("gsm", "audio/x-gsm");
        allContentType.put("gtar", "application/x-tar");
        allContentType.put("gv", "text/vnd.graphviz");
        allContentType.put("gvp", "text/x-google-video-pointer");
        allContentType.put("gz", "application/x-gzip");
        allContentType.put("h", "text/x-chdr");
        allContentType.put("h++", "text/x-c++hdr");
        allContentType.put("hdf", "application/x-hdf");
        allContentType.put("hh", "text/x-c++hdr");
        allContentType.put("hp", "text/x-c++hdr");
        allContentType.put("hpgl", "application/vnd.hp-hpgl");
        allContentType.put("hpp", "text/x-c++hdr");
        allContentType.put("hs", "text/x-haskell");
        allContentType.put("htm", "text/html");
        allContentType.put("html", "text/html");
        allContentType.put("hwp", "application/x-hwp");
        allContentType.put("hwt", "application/x-hwt");
        allContentType.put("hxx", "text/x-c++hdr");
        allContentType.put("ica", "application/x-ica");
        allContentType.put("icb", "image/x-tga");
        allContentType.put("icns", "image/x-icns");
        allContentType.put("ico", "image/vnd.microsoft.icon");
        allContentType.put("ics", "text/calendar");
        allContentType.put("idl", "text/x-idl");
        allContentType.put("ief", "image/ief");
        allContentType.put("iff", "image/x-iff");
        allContentType.put("ilbm", "image/x-ilbm");
        allContentType.put("ime", "text/x-imelody");
        allContentType.put("imy", "text/x-imelody");
        allContentType.put("ins", "text/x-tex");
        allContentType.put("iptables", "text/x-iptables");
        allContentType.put("iso", "application/x-cd-image");
        allContentType.put("iso9660", "application/x-cd-image");
        allContentType.put("it", "audio/x-it");
        allContentType.put("j2k", "image/jp2");
        allContentType.put("jad", "text/vnd.sun.j2me.app-descriptor");
        allContentType.put("jar", "application/x-java-archive");
        allContentType.put("java", "text/x-java");
        allContentType.put("jng", "image/x-jng");
        allContentType.put("jnlp", "application/x-java-jnlp-file");
        allContentType.put("jp2", "image/jp2");
        allContentType.put("jpc", "image/jp2");
        allContentType.put("jpe", "image/jpeg");
        allContentType.put("jpeg", "image/jpeg");
        allContentType.put("jpf", "image/jp2");
        allContentType.put("jpg", "image/jpeg");
        allContentType.put("jpr", "application/x-jbuilder-project");
        allContentType.put("jpx", "image/jp2");
        allContentType.put("js", "application/javascript");
        allContentType.put("json", "application/json");
        allContentType.put("jsonp", "application/jsonp");
        allContentType.put("k25", "image/x-kodak-k25");
        allContentType.put("kar", "audio/midi");
        allContentType.put("karbon", "application/x-karbon");
        allContentType.put("kdc", "image/x-kodak-kdc");
        allContentType.put("kdelnk", "application/x-desktop");
        allContentType.put("kexi", "application/x-kexiproject-sqlite3");
        allContentType.put("kexic", "application/x-kexi-connectiondata");
        allContentType.put("kexis", "application/x-kexiproject-shortcut");
        allContentType.put("kfo", "application/x-kformula");
        allContentType.put("kil", "application/x-killustrator");
        allContentType.put("kino", "application/smil");
        allContentType.put("kml", "application/vnd.google-earth.kml+xml");
        allContentType.put("kmz", "application/vnd.google-earth.kmz");
        allContentType.put("kon", "application/x-kontour");
        allContentType.put("kpm", "application/x-kpovmodeler");
        allContentType.put("kpr", "application/x-kpresenter");
        allContentType.put("kpt", "application/x-kpresenter");
        allContentType.put("kra", "application/x-krita");
        allContentType.put("ksp", "application/x-kspread");
        allContentType.put("kud", "application/x-kugar");
        allContentType.put("kwd", "application/x-kword");
        allContentType.put("kwt", "application/x-kword");
        allContentType.put("la", "application/x-shared-library-la");
        allContentType.put("latex", "text/x-tex");
        allContentType.put("ldif", "text/x-ldif");
        allContentType.put("lha", "application/x-lha");
        allContentType.put("lhs", "text/x-literate-haskell");
        allContentType.put("lhz", "application/x-lhz");
        allContentType.put("log", "text/x-log");
        allContentType.put("ltx", "text/x-tex");
        allContentType.put("lua", "text/x-lua");
        allContentType.put("lwo", "image/x-lwo");
        allContentType.put("lwob", "image/x-lwo");
        allContentType.put("lws", "image/x-lws");
        allContentType.put("ly", "text/x-lilypond");
        allContentType.put("lyx", "application/x-lyx");
        allContentType.put("lz", "application/x-lzip");
        allContentType.put("lzh", "application/x-lha");
        allContentType.put("lzma", "application/x-lzma");
        allContentType.put("lzo", "application/x-lzop");
        allContentType.put("m", "text/x-matlab");
        allContentType.put("m15", "audio/x-mod");
        allContentType.put("m2t", "video/mpeg");
        allContentType.put("m3u", "audio/x-mpegurl");
        allContentType.put("m3u8", "audio/x-mpegurl");
        allContentType.put("m4", "application/x-m4");
        allContentType.put("m4a", "audio/mp4");
        allContentType.put("m4b", "audio/x-m4b");
        allContentType.put("m4v", "video/mp4");
        allContentType.put("mab", "application/x-markaby");
        allContentType.put("man", "application/x-troff-man");
        allContentType.put("mbox", "application/mbox");
        allContentType.put("md", "application/x-genesis-rom");
        allContentType.put("mdb", "application/vnd.ms-access");
        allContentType.put("mdi", "image/vnd.ms-modi");
        allContentType.put("me", "text/x-troff-me");
        allContentType.put("med", "audio/x-mod");
        allContentType.put("metalink", "application/metalink+xml");
        allContentType.put("mgp", "application/x-magicpoint");
        allContentType.put("mid", "audio/midi");
        allContentType.put("midi", "audio/midi");
        allContentType.put("mif", "application/x-mif");
        allContentType.put("minipsf", "audio/x-minipsf");
        allContentType.put("mka", "audio/x-matroska");
        allContentType.put("mkv", "video/x-matroska");
        allContentType.put("ml", "text/x-ocaml");
        allContentType.put("mli", "text/x-ocaml");
        allContentType.put("mm", "text/x-troff-mm");
        allContentType.put("mmf", "application/x-smaf");
        allContentType.put("mml", "text/mathml");
        allContentType.put("mng", "video/x-mng");
        allContentType.put("mo", "application/x-gettext-translation");
        allContentType.put("mo3", "audio/x-mo3");
        allContentType.put("moc", "text/x-moc");
        allContentType.put("mod", "audio/x-mod");
        allContentType.put("mof", "text/x-mof");
        allContentType.put("moov", "video/quicktime");
        allContentType.put("mov", "video/quicktime");
        allContentType.put("movie", "video/x-sgi-movie");
        allContentType.put("mp+", "audio/x-musepack");
        allContentType.put("mp2", "video/mpeg");
        allContentType.put("mp3", "audio/mpeg");
        allContentType.put("mp4", "video/mp4");
        allContentType.put("mpc", "audio/x-musepack");
        allContentType.put("mpe", "video/mpeg");
        allContentType.put("mpeg", "video/mpeg");
        allContentType.put("mpg", "video/mpeg");
        allContentType.put("mpga", "audio/mpeg");
        allContentType.put("mpp", "audio/x-musepack");
        allContentType.put("mrl", "text/x-mrml");
        allContentType.put("mrml", "text/x-mrml");
        allContentType.put("mrw", "image/x-minolta-mrw");
        allContentType.put("ms", "text/x-troff-ms");
        allContentType.put("msi", "application/x-msi");
        allContentType.put("msod", "image/x-msod");
        allContentType.put("msx", "application/x-msx-rom");
        allContentType.put("mtm", "audio/x-mod");
        allContentType.put("mup", "text/x-mup");
        allContentType.put("mxf", "application/mxf");
        allContentType.put("n64", "application/x-n64-rom");
        allContentType.put("nb", "application/mathematica");
        allContentType.put("nc", "application/x-netcdf");
        allContentType.put("nds", "application/x-nintendo-ds-rom");
        allContentType.put("nef", "image/x-nikon-nef");
        allContentType.put("nes", "application/x-nes-rom");
        allContentType.put("nfo", "text/x-nfo");
        allContentType.put("not", "text/x-mup");
        allContentType.put("nsc", "application/x-netshow-channel");
        allContentType.put("nsv", "video/x-nsv");
        allContentType.put("o", "application/x-object");
        allContentType.put("obj", "application/x-tgif");
        allContentType.put("ocl", "text/x-ocl");
        allContentType.put("oda", "application/oda");
        allContentType.put("odb", "application/vnd.oasis.opendocument.database");
        allContentType.put("odc", "application/vnd.oasis.opendocument.chart");
        allContentType.put("odf", "application/vnd.oasis.opendocument.formula");
        allContentType.put("odg", "application/vnd.oasis.opendocument.graphics");
        allContentType.put("odi", "application/vnd.oasis.opendocument.image");
        allContentType.put("odm", "application/vnd.oasis.opendocument.text-master");
        allContentType.put("odp", "application/vnd.oasis.opendocument.presentation");
        allContentType.put("ods", "application/vnd.oasis.opendocument.spreadsheet");
        allContentType.put("odt", "application/vnd.oasis.opendocument.text");
        allContentType.put("oga", "audio/ogg");
        allContentType.put("ogg", "video/x-theora+ogg");
        allContentType.put("ogm", "video/x-ogm+ogg");
        allContentType.put("ogv", "video/ogg");
        allContentType.put("ogx", "application/ogg");
        allContentType.put("old", "application/x-trash");
        allContentType.put("oleo", "application/x-oleo");
        allContentType.put("opml", "text/x-opml+xml");
        allContentType.put("ora", "image/openraster");
        allContentType.put("orf", "image/x-olympus-orf");
        allContentType.put("otc", "application/vnd.oasis.opendocument.chart-template");
        allContentType.put("otf", "application/x-font-otf");
        allContentType.put("otg", "application/vnd.oasis.opendocument.graphics-template");
        allContentType.put("oth", "application/vnd.oasis.opendocument.text-web");
        allContentType.put("otp", "application/vnd.oasis.opendocument.presentation-template");
        allContentType.put("ots", "application/vnd.oasis.opendocument.spreadsheet-template");
        allContentType.put("ott", "application/vnd.oasis.opendocument.text-template");
        allContentType.put("owl", "application/rdf+xml");
        allContentType.put("oxt", "application/vnd.openofficeorg.extension");
        allContentType.put("p", "text/x-pascal");
        allContentType.put("p10", "application/pkcs10");
        allContentType.put("p12", "application/x-pkcs12");
        allContentType.put("p7b", "application/x-pkcs7-certificates");
        allContentType.put("p7s", "application/pkcs7-signature");
        allContentType.put("pack", "application/x-java-pack200");
        allContentType.put("pak", "application/x-pak");
        allContentType.put("par2", "application/x-par2");
        allContentType.put("pas", "text/x-pascal");
        allContentType.put("patch", "text/x-patch");
        allContentType.put("pbm", "image/x-portable-bitmap");
        allContentType.put("pcd", "image/x-photo-cd");
        allContentType.put("pcf", "application/x-cisco-vpn-settings");
        allContentType.put("pcf.gz", "application/x-font-pcf");
        allContentType.put("pcf.z", "application/x-font-pcf");
        allContentType.put("pcl", "application/vnd.hp-pcl");
        allContentType.put("pcx", "image/x-pcx");
        allContentType.put("pdb", "chemical/x-pdb");
        allContentType.put("pdc", "application/x-aportisdoc");
        allContentType.put("pdf", "application/pdf");
        allContentType.put("pdf.bz2", "application/x-bzpdf");
        allContentType.put("pdf.gz", "application/x-gzpdf");
        allContentType.put("pef", "image/x-pentax-pef");
        allContentType.put("pem", "application/x-x509-ca-cert");
        allContentType.put("perl", "application/x-perl");
        allContentType.put("pfa", "application/x-font-type1");
        allContentType.put("pfb", "application/x-font-type1");
        allContentType.put("pfx", "application/x-pkcs12");
        allContentType.put("pgm", "image/x-portable-graymap");
        allContentType.put("pgn", "application/x-chess-pgn");
        allContentType.put("pgp", "application/pgp-encrypted");
        allContentType.put("php", "application/x-php");
        allContentType.put("php3", "application/x-php");
        allContentType.put("php4", "application/x-php");
        allContentType.put("pict", "image/x-pict");
        allContentType.put("pict1", "image/x-pict");
        allContentType.put("pict2", "image/x-pict");
        allContentType.put("pickle", "application/python-pickle");
        allContentType.put("pk", "application/x-tex-pk");
        allContentType.put("pkipath", "application/pkix-pkipath");
        allContentType.put("pkr", "application/pgp-keys");
        allContentType.put("pl", "application/x-perl");
        allContentType.put("pla", "audio/x-iriver-pla");
        allContentType.put("pln", "application/x-planperfect");
        allContentType.put("pls", "audio/x-scpls");
        allContentType.put("pm", "application/x-perl");
        allContentType.put("png", "image/png");
        allContentType.put("pnm", "image/x-portable-anymap");
        allContentType.put("pntg", "image/x-macpaint");
        allContentType.put("po", "text/x-gettext-translation");
        allContentType.put("por", "application/x-spss-por");
        allContentType.put("pot", "text/x-gettext-translation-template");
        allContentType.put("ppm", "image/x-portable-pixmap");
        allContentType.put("pps", "application/vnd.ms-powerpoint");
        allContentType.put("ppt", "application/vnd.ms-powerpoint");
        allContentType.put("pptm", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
        allContentType.put("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
        allContentType.put("ppz", "application/vnd.ms-powerpoint");
        allContentType.put("prc", "application/x-palm-database");
        allContentType.put("ps", "application/postscript");
        allContentType.put("ps.bz2", "application/x-bzpostscript");
        allContentType.put("ps.gz", "application/x-gzpostscript");
        allContentType.put("psd", "image/vnd.adobe.photoshop");
        allContentType.put("psf", "audio/x-psf");
        allContentType.put("psf.gz", "application/x-gz-font-linux-psf");
        allContentType.put("psflib", "audio/x-psflib");
        allContentType.put("psid", "audio/prs.sid");
        allContentType.put("psw", "application/x-pocket-word");
        allContentType.put("pw", "application/x-pw");
        allContentType.put("py", "text/x-python");
        allContentType.put("pyc", "application/x-python-bytecode");
        allContentType.put("pyo", "application/x-python-bytecode");
        allContentType.put("qif", "image/x-quicktime");
        allContentType.put("qt", "video/quicktime");
        allContentType.put("qtif", "image/x-quicktime");
        allContentType.put("qtl", "application/x-quicktime-media-link");
        allContentType.put("qtvr", "video/quicktime");
        allContentType.put("ra", "audio/vnd.rn-realaudio");
        allContentType.put("raf", "image/x-fuji-raf");
        allContentType.put("ram", "application/ram");
        allContentType.put("rar", "application/x-rar");
        allContentType.put("ras", "image/x-cmu-raster");
        allContentType.put("raw", "image/x-panasonic-raw");
        allContentType.put("rax", "audio/vnd.rn-realaudio");
        allContentType.put("rb", "application/x-ruby");
        allContentType.put("rdf", "application/rdf+xml");
        allContentType.put("rdfs", "application/rdf+xml");
        allContentType.put("reg", "text/x-ms-regedit");
        allContentType.put("rej", "application/x-reject");
        allContentType.put("rgb", "image/x-rgb");
        allContentType.put("rle", "image/rle");
        allContentType.put("rm", "application/vnd.rn-realmedia");
        allContentType.put("rmj", "application/vnd.rn-realmedia");
        allContentType.put("rmm", "application/vnd.rn-realmedia");
        allContentType.put("rms", "application/vnd.rn-realmedia");
        allContentType.put("rmvb", "application/vnd.rn-realmedia");
        allContentType.put("rmx", "application/vnd.rn-realmedia");
        allContentType.put("roff", "text/troff");
        allContentType.put("rp", "image/vnd.rn-realpix");
        allContentType.put("rpm", "application/x-rpm");
        allContentType.put("rss", "application/rss+xml");
        allContentType.put("rt", "text/vnd.rn-realtext");
        allContentType.put("rtf", "application/rtf");
        allContentType.put("rtx", "text/richtext");
        allContentType.put("rv", "video/vnd.rn-realvideo");
        allContentType.put("rvx", "video/vnd.rn-realvideo");
        allContentType.put("s3m", "audio/x-s3m");
        allContentType.put("sam", "application/x-amipro");
        allContentType.put("sami", "application/x-sami");
        allContentType.put("sav", "application/x-spss-sav");
        allContentType.put("scm", "text/x-scheme");
        allContentType.put("sda", "application/vnd.stardivision.draw");
        allContentType.put("sdc", "application/vnd.stardivision.calc");
        allContentType.put("sdd", "application/vnd.stardivision.impress");
        allContentType.put("sdp", "application/sdp");
        allContentType.put("sds", "application/vnd.stardivision.chart");
        allContentType.put("sdw", "application/vnd.stardivision.writer");
        allContentType.put("sgf", "application/x-go-sgf");
        allContentType.put("sgi", "image/x-sgi");
        allContentType.put("sgl", "application/vnd.stardivision.writer");
        allContentType.put("sgm", "text/sgml");
        allContentType.put("sgml", "text/sgml");
        allContentType.put("sh", "application/x-shellscript");
        allContentType.put("shar", "application/x-shar");
        allContentType.put("shn", "application/x-shorten");
        allContentType.put("siag", "application/x-siag");
        allContentType.put("sid", "audio/prs.sid");
        allContentType.put("sik", "application/x-trash");
        allContentType.put("sis", "application/vnd.symbian.install");
        allContentType.put("sisx", "x-epoc/x-sisx-app");
        allContentType.put("sit", "application/x-stuffit");
        allContentType.put("siv", "application/sieve");
        allContentType.put("sk", "image/x-skencil");
        allContentType.put("sk1", "image/x-skencil");
        allContentType.put("skr", "application/pgp-keys");
        allContentType.put("slk", "text/spreadsheet");
        allContentType.put("smaf", "application/x-smaf");
        allContentType.put("smc", "application/x-snes-rom");
        allContentType.put("smd", "application/vnd.stardivision.mail");
        allContentType.put("smf", "application/vnd.stardivision.math");
        allContentType.put("smi", "application/x-sami");
        allContentType.put("smil", "application/smil");
        allContentType.put("sml", "application/smil");
        allContentType.put("sms", "application/x-sms-rom");
        allContentType.put("snd", "audio/basic");
        allContentType.put("so", "application/x-sharedlib");
        allContentType.put("spc", "application/x-pkcs7-certificates");
        allContentType.put("spd", "application/x-font-speedo");
        allContentType.put("spec", "text/x-rpm-spec");
        allContentType.put("spl", "application/x-shockwave-flash");
        allContentType.put("spx", "audio/x-speex");
        allContentType.put("sql", "text/x-sql");
        allContentType.put("sr2", "image/x-sony-sr2");
        allContentType.put("src", "application/x-wais-source");
        allContentType.put("srf", "image/x-sony-srf");
        allContentType.put("srt", "application/x-subrip");
        allContentType.put("ssa", "text/x-ssa");
        allContentType.put("stc", "application/vnd.sun.xml.calc.template");
        allContentType.put("std", "application/vnd.sun.xml.draw.template");
        allContentType.put("sti", "application/vnd.sun.xml.impress.template");
        allContentType.put("stm", "audio/x-stm");
        allContentType.put("stw", "application/vnd.sun.xml.writer.template");
        allContentType.put("sty", "text/x-tex");
        allContentType.put("sub", "text/x-subviewer");
        allContentType.put("sun", "image/x-sun-raster");
        allContentType.put("sv4cpio", "application/x-sv4cpio");
        allContentType.put("sv4crc", "application/x-sv4crc");
        allContentType.put("svg", "image/svg+xml");
        allContentType.put("svgz", "image/svg+xml-compressed");
        allContentType.put("swf", "application/x-shockwave-flash");
        allContentType.put("sxc", "application/vnd.sun.xml.calc");
        allContentType.put("sxd", "application/vnd.sun.xml.draw");
        allContentType.put("sxg", "application/vnd.sun.xml.writer.global");
        allContentType.put("sxi", "application/vnd.sun.xml.impress");
        allContentType.put("sxm", "application/vnd.sun.xml.math");
        allContentType.put("sxw", "application/vnd.sun.xml.writer");
        allContentType.put("sylk", "text/spreadsheet");
        allContentType.put("t", "text/troff");
        allContentType.put("t2t", "text/x-txt2tags");
        allContentType.put("tar", "application/x-tar");
        allContentType.put("tar.bz", "application/x-bzip-compressed-tar");
        allContentType.put("tar.bz2", "application/x-bzip-compressed-tar");
        allContentType.put("tar.gz", "application/x-compressed-tar");
        allContentType.put("tar.lzma", "application/x-lzma-compressed-tar");
        allContentType.put("tar.lzo", "application/x-tzo");
        allContentType.put("tar.xz", "application/x-xz-compressed-tar");
        allContentType.put("tar.z", "application/x-tarz");
        allContentType.put("tbz", "application/x-bzip-compressed-tar");
        allContentType.put("tbz2", "application/x-bzip-compressed-tar");
        allContentType.put("tcl", "text/x-tcl");
        allContentType.put("tex", "text/x-tex");
        allContentType.put("texi", "text/x-texinfo");
        allContentType.put("texinfo", "text/x-texinfo");
        allContentType.put("tga", "image/x-tga");
        allContentType.put("tgz", "application/x-compressed-tar");
        allContentType.put("theme", "application/x-theme");
        allContentType.put("themepack", "application/x-windows-themepack");
        allContentType.put("tif", "image/tiff");
        allContentType.put("tiff", "image/tiff");
        allContentType.put("tk", "text/x-tcl");
        allContentType.put("tlz", "application/x-lzma-compressed-tar");
        allContentType.put("tnef", "application/vnd.ms-tnef");
        allContentType.put("tnf", "application/vnd.ms-tnef");
        allContentType.put("toc", "application/x-cdrdao-toc");
        allContentType.put("torrent", "application/x-bittorrent");
        allContentType.put("tpic", "image/x-tga");
        allContentType.put("tr", "text/troff");
        allContentType.put("ts", "application/x-linguist");
        allContentType.put("tsv", "text/tab-separated-values");
        allContentType.put("tta", "audio/x-tta");
        allContentType.put("ttc", "application/x-font-ttf");
        allContentType.put("ttf", "application/x-font-ttf");
        allContentType.put("ttx", "application/x-font-ttx");
        allContentType.put("txt", "text/plain");
        allContentType.put("txz", "application/x-xz-compressed-tar");
        allContentType.put("tzo", "application/x-tzo");
        allContentType.put("ufraw", "application/x-ufraw");
        allContentType.put("ui", "application/x-designer");
        allContentType.put("uil", "text/x-uil");
        allContentType.put("ult", "audio/x-mod");
        allContentType.put("uni", "audio/x-mod");
        allContentType.put("uri", "text/x-uri");
        allContentType.put("url", "text/x-uri");
        allContentType.put("ustar", "application/x-ustar");
        allContentType.put("vala", "text/x-vala");
        allContentType.put("vapi", "text/x-vala");
        allContentType.put("vcf", "text/directory");
        allContentType.put("vcs", "text/calendar");
        allContentType.put("vct", "text/directory");
        allContentType.put("vda", "image/x-tga");
        allContentType.put("vhd", "text/x-vhdl");
        allContentType.put("vhdl", "text/x-vhdl");
        allContentType.put("viv", "video/vivo");
        allContentType.put("vivo", "video/vivo");
        allContentType.put("vlc", "audio/x-mpegurl");
        allContentType.put("vob", "video/mpeg");
        allContentType.put("voc", "audio/x-voc");
        allContentType.put("vor", "application/vnd.stardivision.writer");
        allContentType.put("vst", "image/x-tga");
        allContentType.put("wav", "audio/x-wav");
        allContentType.put("wax", "audio/x-ms-asx");
        allContentType.put("wb1", "application/x-quattropro");
        allContentType.put("wb2", "application/x-quattropro");
        allContentType.put("wb3", "application/x-quattropro");
        allContentType.put("wbmp", "image/vnd.wap.wbmp");
        allContentType.put("wcm", "application/vnd.ms-works");
        allContentType.put("wdb", "application/vnd.ms-works");
        allContentType.put("webm", "video/webm");
        allContentType.put("wk1", "application/vnd.lotus-1-2-3");
        allContentType.put("wk3", "application/vnd.lotus-1-2-3");
        allContentType.put("wk4", "application/vnd.lotus-1-2-3");
        allContentType.put("wks", "application/vnd.ms-works");
        allContentType.put("wma", "audio/x-ms-wma");
        allContentType.put("wmf", "image/x-wmf");
        allContentType.put("wml", "text/vnd.wap.wml");
        allContentType.put("wmls", "text/vnd.wap.wmlscript");
        allContentType.put("wmv", "video/x-ms-wmv");
        allContentType.put("wmx", "audio/x-ms-asx");
        allContentType.put("wp", "application/vnd.wordperfect");
        allContentType.put("wp4", "application/vnd.wordperfect");
        allContentType.put("wp5", "application/vnd.wordperfect");
        allContentType.put("wp6", "application/vnd.wordperfect");
        allContentType.put("wpd", "application/vnd.wordperfect");
        allContentType.put("wpg", "application/x-wpg");
        allContentType.put("wpl", "application/vnd.ms-wpl");
        allContentType.put("wpp", "application/vnd.wordperfect");
        allContentType.put("wps", "application/vnd.ms-works");
        allContentType.put("wri", "application/x-mswrite");
        allContentType.put("wrl", "model/vrml");
        allContentType.put("wv", "audio/x-wavpack");
        allContentType.put("wvc", "audio/x-wavpack-correction");
        allContentType.put("wvp", "audio/x-wavpack");
        allContentType.put("wvx", "audio/x-ms-asx");
        allContentType.put("x3f", "image/x-sigma-x3f");
        allContentType.put("xac", "application/x-gnucash");
        allContentType.put("xbel", "application/x-xbel");
        allContentType.put("xbl", "application/xml");
        allContentType.put("xbm", "image/x-xbitmap");
        allContentType.put("xcf", "image/x-xcf");
        allContentType.put("xcf.bz2", "image/x-compressed-xcf");
        allContentType.put("xcf.gz", "image/x-compressed-xcf");
        allContentType.put("xhtml", "application/xhtml+xml");
        allContentType.put("xi", "audio/x-xi");
        allContentType.put("xla", "application/vnd.ms-excel");
        allContentType.put("xlc", "application/vnd.ms-excel");
        allContentType.put("xld", "application/vnd.ms-excel");
        allContentType.put("xlf", "application/x-xliff");
        allContentType.put("xliff", "application/x-xliff");
        allContentType.put("xll", "application/vnd.ms-excel");
        allContentType.put("xlm", "application/vnd.ms-excel");
        allContentType.put("xls", "application/vnd.ms-excel");
        allContentType.put("xlsm", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        allContentType.put("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        allContentType.put("xlt", "application/vnd.ms-excel");
        allContentType.put("xlw", "application/vnd.ms-excel");
        allContentType.put("xm", "audio/x-xm");
        allContentType.put("xmf", "audio/x-xmf");
        allContentType.put("xmi", "text/x-xmi");
        allContentType.put("xml", "application/xml");
        allContentType.put("xpm", "image/x-xpixmap");
        allContentType.put("xps", "application/vnd.ms-xpsdocument");
        allContentType.put("xsl", "application/xml");
        allContentType.put("xslfo", "text/x-xslfo");
        allContentType.put("xslt", "application/xml");
        allContentType.put("xspf", "application/xspf+xml");
        allContentType.put("xul", "application/vnd.mozilla.xul+xml");
        allContentType.put("xwd", "image/x-xwindowdump");
        allContentType.put("xyz", "chemical/x-pdb");
        allContentType.put("xz", "application/x-xz");
        allContentType.put("w2p", "application/w2p");
        allContentType.put("z", "application/x-compress");
        allContentType.put("zabw", "application/x-abiword");
        allContentType.put("zip", "application/zip");
    }

}
